output_dir: '/home/dinesh/Documents/Projects/BTP weights/CDCN/output/'
log_dir: 'experiments/log'
device: '0'
dataset:
  name: 'OULU-NPU'
  root: '/home/dinesh/Documents/Projects/CDCN/'
  augmentation:
    horizontal_flip: True
    rotation_range: 10
    gamma_correction: [0.67, 1.5]
    brightness: 0.5
    contrast: 0.5
    saturation: 0.5
    hue: 0.5
  train_set: 'train_data.csv'
  val_set: 'dev_data.csv'
  test_set: 'test_data.csv'
  mean: [0.5,0.5,0.5]
  sigma: [0.5,0.5,0.5]
model:
  base: 'CDCNpp'
  pretrained: false
  input_size: [224,224]
  depth_map_size: [32,32]
train:
  batch_size: 64
  optimizer: 'adam'
  lr: 0.0001
  num_epochs: 10
  smoothing: True
val:
  batch_size: 64
test:
  batch_size: 64

